// Generated by CoffeeScript 1.9.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.Deck = (function(superClass) {
    extend(Deck, superClass);

    function Deck() {
      return Deck.__super__.constructor.apply(this, arguments);
    }

    Deck.prototype.model = Card;

    Deck.prototype.initialize = function() {
      var i, results;
      return this.add(_((function() {
        results = [];
        for (i = 0; i <= 51; i++){ results.push(i); }
        return results;
      }).apply(this)).shuffle().map(function(card) {
        return new Card({
          rank: card % 13,
          suit: Math.floor(card / 13)
        });
      }));
    };

    Deck.prototype.dealPlayer = function() {
      return new Hand([this.pop(), this.pop()], this);
    };

    Deck.prototype.dealDealer = function() {
      return new Hand([this.pop().flip(), this.pop()], this, true);
    };

    return Deck;

  })(Backbone.Collection);

}).call(this);

//# sourceMappingURL=Deck.js.map
