// Generated by CoffeeScript 1.9.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.CardView = (function(superClass) {
    extend(CardView, superClass);

    function CardView() {
      return CardView.__super__.constructor.apply(this, arguments);
    }

    CardView.prototype.className = 'card';

    CardView.prototype.template = _.template('');

    CardView.prototype.initialize = function() {
      return this.render();
    };

    CardView.prototype.render = function() {
      var bgUrl, suitLower;
      this.$el.children().detach();
      this.$el.html(this.template(this.model.attributes));
      if (!this.model.get('revealed')) {
        this.$el.addClass('covered');
      }
      suitLower = this.model.get('suitName').toLowerCase();
      bgUrl = "url('img/" + (this.model.get('rankName')) + "-" + suitLower + ".png')";
      this.$el.css({
        'background': bgUrl,
        'background-size': '120px, 167px'
      });
      if (!this.model.get('revealed')) {
        return this.$el.css({
          'background': "url('img/card-back.png')",
          'background-size': '120px, 167px'
        });
      }
    };

    return CardView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=CardView.js.map
