// Generated by CoffeeScript 1.9.0
(function() {
  var assert;

  assert = chai.assert;

  describe('deck', function() {
    var apl, deck, hand, hand2;
    deck = null;
    hand = null;
    hand2 = null;
    apl = null;
    return beforeEach(function() {
      apl = new AppView({
        model: new App()
      });
      deck = apl.model.get('deck');
      hand = apl.model.get('playerHand');
      return hand2 = apl.model.get('dealerHand');
    });
  });

  describe('show dealer hand', function() {
    return it('when player stands then show dealers down card', function() {
      var temp, temp2;
      temp = hand2.scores()[0];
      hand.stand();
      temp2 = hand2.scores()[0];
      return assert.notStrictEqual(temp, temp2);
    });
  });

}).call(this);

//# sourceMappingURL=BlackjackViewSpec.js.map
