// Generated by CoffeeScript 1.9.0
(function() {
  var assert;

  assert = chai.assert;

  describe('deck', function() {
    var deck, hand, hand2;
    deck = null;
    hand = null;
    hand2 = null;
    beforeEach(function() {
      deck = new Deck();
      hand = deck.dealPlayer();
      return hand2 = deck.dealDealer();
    });
    describe('hit', function() {
      return it('should give the last card from the deck', function() {
        assert.strictEqual(deck.length, 48);
        assert.strictEqual(deck.last(), hand.hit());
        return assert.strictEqual(deck.length, 47);
      });
    });
    return describe('stand', function() {
      return it('when player stands then dealer should play', function() {
        assert.strictEqual(deck.length, 48);
        hand2.hit();
        return assert.strictEqual(deck.length, 47);
      });
    });
  });

}).call(this);

//# sourceMappingURL=DeckSpec.js.map
